// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_automode.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_openingscreen.cpp"
#include "EWIEGA46WW/moc_qcustomplot.cpp"
#include "EWIEGA46WW/moc_tuningplot1.cpp"
